// Pixel art, drawn as grids rather than curves.
//
// The retro theme is a desktop from the era when an icon was a small number of
// square pixels placed by hand, so these are placed by hand. `x` is the ink,
// `o` the second colour, `.` nothing. Rendered by `ui/Pixels.vue`, which turns
// each row into one path so a 16-square icon is one element and not sixteen.

export type Art =
  | "home" | "folder" | "drain" | "history" | "settings"
  | "no-folders" | "no-runs" | "no-pairs" | "no-connections" | "no-archives" | "nothing-found"
  | "no-history";

/** The four section marks, eight squares across, to sit in a 22pt tile. */
const SECTIONS: Record<string, string[]> = {
  home: [
    "...xx...",
    "..xxxx..",
    ".xx..xx.",
    "xx....xx",
    ".xoooox.",
    ".xo..ox.",
    ".xo..ox.",
    ".xxxxxx.",
  ],
  folder: [
    "........",
    ".xxx....",
    ".x..xxx.",
    ".xoooox.",
    ".xoooox.",
    ".xoooox.",
    ".xxxxxx.",
    "........",
  ],
  drain: [
    ".xxxxxx.",
    ".xoooox.",
    ".xxxxxx.",
    "...xx...",
    ".x.xx.x.",
    "..xxxx..",
    ".xxxxxx.",
    ".xoooox.",
  ],
  history: [
    "..xxxx..",
    ".x....x.",
    "x..x...x",
    "x..x...x",
    "x..xxx.x",
    "x......x",
    ".x....x.",
    "..xxxx..",
  ],
  settings: [
    "........",
    "..x.....",
    "xxxxxxxx",
    "..x.....",
    ".....x..",
    "xxxxxxxx",
    ".....x..",
    "........",
  ],
};

/** Empty states, sixteen squares across: a scene rather than a symbol. */
const SCENES: Record<string, string[]> = {
  "no-folders": [
    "................",
    "................",
    "..xxxxx.........",
    "..x...xxxxxxxx..",
    "..x...........x.",
    "..x....ooo....x.",
    "..x....ooo....x.",
    "..x.ooooooooo.x.",
    "..x.ooooooooo.x.",
    "..x....ooo....x.",
    "..x....ooo....x.",
    "..x...........x.",
    "..xxxxxxxxxxxxx.",
    "................",
    "................",
    "................",
  ],
  "no-runs": [
    "................",
    ".......xx.......",
    ".......xx.......",
    ".......xx.......",
    "....x..xx..x....",
    ".....x.xx.x.....",
    "......xxxx......",
    ".......xx.......",
    "................",
    "..xxxxxxxxxxxx..",
    "..x..........x..",
    "..x.oooooooo.x..",
    "..x..........x..",
    "..xxxxxxxxxxxx..",
    "................",
    "................",
  ],
  "no-pairs": [
    "................",
    "................",
    ".xxxxx....xxxxx.",
    ".x...x....x...x.",
    ".x.o.x.xx.x.o.x.",
    ".x...x.xx.x...x.",
    ".xxxxx....xxxxx.",
    "..xxx......xxx..",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  "no-connections": [
    "................",
    "................",
    ".....xx..xx.....",
    ".....xx..xx.....",
    "....xxxxxxxx....",
    "....xoooooox....",
    "....xxxxxxxx....",
    "......xxxx......",
    "......xxxx......",
    ".....xxxxxx.....",
    ".....x....x.....",
    ".....x.oo.x.....",
    ".....xxxxxx.....",
    "................",
    "................",
    "................",
  ],
  "no-history": [
    "................",
    "..xxxxxxxxxxxx..",
    "..x..........x..",
    "..x.oo.ooooo.x..",
    "..x..........x..",
    "..x.oo.ooooo.x..",
    "..x..........x..",
    "..x.oo.ooooo.x..",
    "..x..........x..",
    "..x.oo.ooooo.x..",
    "..x..........x..",
    "..xxxxxxxxxxxx..",
    "................",
    "................",
    "................",
    "................",
  ],
  "no-archives": [
    "................",
    "................",
    "..xxxxxxxxxxxx..",
    "..x..........x..",
    "..x.oooooooo.x..",
    "..x..........x..",
    "..xxxxxxxxxxxx..",
    "..x..........x..",
    "..x...xxxx...x..",
    "..x..........x..",
    "..x..........x..",
    "..xxxxxxxxxxxx..",
    "................",
    "................",
    "................",
    "................",
  ],
  "nothing-found": [
    "................",
    "....xxxxxx......",
    "...x......x.....",
    "..x..oooo..x....",
    "..x.oo..oo.x....",
    "..x.oo..oo.x....",
    "..x..oooo..x....",
    "...x......x.....",
    "....xxxxxx......",
    "..........xx....",
    "...........xx...",
    "............xx..",
    ".............xx.",
    "................",
    "................",
    "................",
  ],
};

export const ART: Record<Art, string[]> = { ...SECTIONS, ...SCENES } as Record<Art, string[]>;
