[package]
name = "tungstate-transfer"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
tungstate-backend = { path = "../tungstate-backend" }
tungstate-journal = { path = "../tungstate-journal" }
blake3 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
trash = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
